name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '13.2'
            host: macos-12

# Only FreeBSD ATM
#          - name: openbsd
#            architecture: x86-64
#            version: '7.3'
#            host: macos-12
#
#          - name: openbsd
#            architecture: arm64
#            version: '7.3'
#            host: ubuntu-latest
#
#          - name: netbsd
#            architecture: x86-64
#            version: '9.2'
#            host: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.13.0
        env:
          PATH: /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/runner/bin
        with:
          environment_variables: PATH
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: default
          memory: 8G
          cpu_count: 4
          run: |
            uname -a
            echo $SHELL
            pwd
            ls -lah
            whoami
            env | sort
            sudo pkg install -y shells/bash && echo "bash installed"
            sudo pkg install -y devel/py-tox textproc/py-tomli && echo "tox installed"
            echo $PATH
            which bash
            tox -e local-sudo-freebsd-standard
